### ISSUE TITLE
probleme d'install lpack

### ISSUE THREAD

**Issue by jbloit** [spectrenoir06/plantoid-led-master#1]
Hello, 

Merci pour le code. Je ne pratique pas du tout LUA, je viens d'essayer d'installer (macos 10.12.6) et ca coince à l'installe de lpack. Any idea?

`humtaps-MBP:plantoid-led-master julien$ luarocks install lpack
Warning: The directory '/Users/julien/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /usr/local/bin/luarocks with sudo, you may want sudo's -H flag.
Warning: falling back to curl - install luasec to get native HTTPS support
Installing https://luarocks.org/lpack-20070629-1.src.rock
Do not use 'module' as a build type. Use 'builtin' instead.
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include/lua5.3 -c lpack.c -o lpack.o
lpack.c:254:14: error: unknown type name 'luaL_reg'; did you mean 'luaL_Reg'?
static const luaL_reg R[] =
             ^~~~~~~~
             luaL_Reg
/usr/local/include/lua5.3/lauxlib.h:34:3: note: 'luaL_Reg' declared here
} luaL_Reg;
  ^
lpack.c:267:2: warning: implicit declaration of function 'luaL_openlib' is invalid in C99
      [-Wimplicit-function-declaration]
 luaL_openlib(L, LUA_STRLIBNAME, R, 0);
 ^
1 warning and 1 error generated.

Error: Build error: Failed compiling object lpack.o`

**Comment by spectrenoir06** [comment]
T'as whats app ?

**Comment by spectrenoir06** [comment]
tu as quelle version de lua sur ton ordi ?

**Comment by jbloit** [comment]
Lua 5.3.4

**Comment by spectrenoir06** [comment]
test avec lua5.1 ou luajit

**Comment by jbloit** [comment]
C'est bon ca marche avec 5.1
(je fais tourner sur un linux maintenant)

Merci
